### ISSUE TITLE
npm install runs into Permission denied

### ISSUE THREAD

**Issue by imrek** [derhuerst/asciicast-to-svg#5]
I can install other things with `npm`, just not `asciicast-to-svg`.

With or without sudo, I ran into` npmERR! Command failed: /usr/bin/git clone -q <your-repo> /home/user/.npm/_cacache/tmp/git-clone-6bd4e853`

```
npm --version
5.6.0
```

```
nodejs --version
v10.2.1
```

**Comment by derhuerst** [comment]
> `Command failed: /usr/bin/git clone -q <your-repo>`

Where does this come from? Please provide the full log.

**Comment by derhuerst** [comment]
please reopen if you still have this error.
